sonar.projectKey=aminebella_smartflowmanually

sonar.sources=.

sonar.token=70ec0242b757c1d4c16d45b1e35e0f6d431ef8f4

sonar.sourceEncoding=UTF-8

sonar.java.binaries=bin

sonar.host.url=https://sonarcloud.io

sonar.organization=aminebella