# the name of the app
spring.application.name=SmartFlow

# Database MySQL
# MySQL database named "SmartFlow_db"
spring.datasource.url=jdbc:mysql://localhost:3306/SmartFlow_db
spring.datasource.username=root
#root123
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
# DROPS and RE-CREATES all tables on every restart, we will use "update" for production to avoid data loss
spring.jpa.hibernate.ddl-auto=create
# Print SQL queries in the console (useful for debugging)
spring.jpa.show-sql=true
# Make those printed SQL queries readable (formatted)
spring.jpa.properties.hibernate.format_sql=true

# API Docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs
# Server
# App runs on port 8080
server.port=8080
# ALL routes start with /api/v1/ automatically
server.servlet.context-path=/api/v1/
# So "auth/register" becomes "http://localhost:8080/api/v1/auth/register"

# JWT Security
# The secret used to sign JWT tokens, should be long and random for security. In production, store this securely (e.g., environment variable or secrets manager)
application.security.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#JWT expires in 86400000 ms = 24 hours
application.security.expiration=86400000
application.security.refresh-token.expiration=604800000

# Mail (MailDev local)
# Using MailDev (a local fake email server for dev, like Mailtrap)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=ana
spring.mail.password=ana
spring.mail.properties.mail.smtp.trust=*
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enabled=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.protocol=smtp

# Activation URL : For Next js Frontend
application.mailing.frontend.activation-url=http://localhost:3000/activate-account
#application.mailing.frontend.activation-url=http://localhost:4200/activate-account